// Dữ liệu mẫu - đây là "database text" tạm thời
const productsData = [
  {
    id: 1,
    title: "iPhone 14 Pro Max 256GB màu đen, mới 99%",
    price: 25000000,
    category: "electronics",
    categoryName: "Điện tử",
    condition: "Đã sử dụng (như mới)",
    location: "Quận 1, TP. Hồ Chí Minh",
    date: "02/05/2025",
    seller: "Trần Văn Bình",
    description:
      "iPhone 14 Pro Max màu đen, dung lượng 256GB. Máy mới mua được 3 tháng, còn bảo hành chính hãng 9 tháng. Pin 99%, full phụ kiện nguyên seal. Lý do bán: đổi máy mới. Giá có thể thương lượng với người thiện chí.",
    images: ["iphone.jpg"],
  },
  {
    id: 2,
    title: "Honda SH 150i đời 2023, màu đỏ",
    price: 88000000,
    category: "vehicle",
    categoryName: "Xe cộ",
    condition: "Đã sử dụng (tốt)",
    location: "Quận Cầu Giấy, Hà Nội",
    date: "03/05/2025",
    seller: "Nguyễn Thị Hương",
    description:
      "Bán xe Honda SH 150i đời 2023, màu đỏ. Xe nữ sử dụng, ít đi, đồng hồ 5,000km. Xe còn mới đẹp, máy êm, chưa đâm đụng hay ngập nước. Giấy tờ chính chủ, sang tên trong ngày.",
    images: ["honda-sh.jpg"],
  },
  {
    id: 3,
    title: "Căn hộ chung cư Vinhomes 2 phòng ngủ",
    price: 2800000000,
    category: "property",
    categoryName: "Bất động sản",
    condition: "Mới",
    location: "Quận 9, TP. Hồ Chí Minh",
    date: "01/05/2025",
    seller: "Phạm Minh Đức",
    description:
      "Bán căn hộ chung cư Vinhomes 2 phòng ngủ, 2 WC, 72m2. Căn hộ mới bàn giao, view sông thoáng mát. Nội thất cơ bản từ chủ đầu tư. Khu vực an ninh, tiện ích đầy đủ: hồ bơi, gym, công viên, trường học... Sổ hồng trao tay.",
    images: ["apartment.jpg"],
  },
  {
    id: 4,
    title: "Tuyển nhân viên kinh doanh BĐS - Thu nhập 20-50tr",
    price: 0,
    category: "job",
    categoryName: "Việc làm",
    condition: "Toàn thời gian",
    location: "Quận Đống Đa, Hà Nội",
    date: "01/05/2025",
    seller: "Công ty BĐS Thành Công",
    description:
      "Tuyển nhân viên kinh doanh bất động sản. Yêu cầu: năng động, giao tiếp tốt, nhanh nhẹn. Không yêu cầu kinh nghiệm, được đào tạo từ cơ bản đến chuyên sâu. Lương cơ bản 8tr + hoa hồng cao. Thu nhập trung bình 20-50tr/tháng.",
    images: ["job.jpg"],
  },
  {
    id: 5,
    title: "MacBook Pro M2 Pro 16 inch 2023",
    price: 42000000,
    category: "electronics",
    categoryName: "Điện tử",
    condition: "Đã sử dụng (như mới)",
    location: "Quận 7, TP. Hồ Chí Minh",
    date: "30/04/2025",
    seller: "Lê Minh Tú",
    description:
      "Bán MacBook Pro 16 inch 2023, chip M2 Pro, RAM 16GB, SSD 512GB. Máy mua tại Apple Store Singapore tháng 2/2025, còn bảo hành quốc tế. Máy đẹp như mới, pin 97%, mọi chức năng hoạt động tốt. Lý do bán: thừa máy.",
    images: ["macbook.jpg"],
  },
  {
    id: 6,
    title: "Bàn làm việc gỗ tự nhiên",
    price: 3500000,
    category: "furniture",
    categoryName: "Nội thất",
    condition: "Mới",
    location: "Quận 2, TP. Hồ Chí Minh",
    date: "29/04/2025",
    seller: "Xưởng gỗ Thành Long",
    description:
      "Bàn làm việc gỗ tự nhiên cao cấp, kiểu dáng hiện đại. Kích thước 120x60x75cm. Gỗ sồi Mỹ, sơn PU cao cấp, chống xước, chống nước. Có ngăn kéo tiện dụng. Sản phẩm mới 100%, bảo hành 12 tháng.",
    images: ["desk.jpg"],
  },
  {
    id: 7,
    title: "Cho thuê mặt bằng kinh doanh 50m2",
    price: 15000000,
    category: "property",
    categoryName: "Bất động sản",
    condition: "Đã sử dụng (tốt)",
    location: "Quận Ba Đình, Hà Nội",
    date: "28/04/2025",
    seller: "Trịnh Văn Nam",
    description:
      "Cho thuê mặt bằng kinh doanh đường Đội Cấn, quận Ba Đình. Diện tích 50m2, mặt tiền 5m, vỉa hè rộng. Khu vực đông dân cư, kinh doanh sầm uất. Phù hợp mở cửa hàng thời trang, spa, café,... Giá 15tr/tháng, hợp đồng dài hạn.",
    images: ["shop-space.jpg"],
  },
  {
    id: 8,
    title: "Áo khoác nam hàng hiệu Calvin Klein",
    price: 2500000,
    category: "fashion",
    categoryName: "Thời trang",
    condition: "Mới",
    location: "Quận 3, TP. Hồ Chí Minh",
    date: "27/04/2025",
    seller: "Shop thời trang Nam Định",
    description:
      "Áo khoác nam Calvin Klein chính hãng. Mẫu mới nhất 2025, nhập khẩu trực tiếp từ Mỹ. Size M, L, XL. Chất liệu cao cấp, giữ ấm tốt. Thiết kế hiện đại, sang trọng, phù hợp mọi dịp.",
    images: ["jacket.jpg"],
  },
];
